### ISSUE TITLE
读不了图片

### ISSUE THREAD

**Issue by Youth-Got** [zheng-yuwei/RankIQA.PyTorch#6]
作者您好，my_dataloader方法读不了图片呢，debug发现transform_list中cv2.read返回的是None，而不是image，这个问题您有经验吗？

**Comment by zheng-yuwei** [comment]
> 作者您好，my_dataloader方法读不了图片呢，debug发现transform_list中cv2.read返回的是None，而不是image，这个问题您有经验吗？

图片不存在？
